language: node_js

node_js:
  - "6"
  - "7.10"
  - "8.4"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - yarn build

  - if node bin/checkpack.js webpack -e tests/bad_build.ts --validate; then (exit 1) else (exit 0) fi
  - node bin/checkpack.js webpack -e tests/good_build.ts --validate

  - if node bin/checkpack.js vanillajs -e tests/bad_build.ts --validate; then (exit 1) else (exit 0) fi
  - node bin/checkpack.js vanillajs -e tests/good_build.ts --validate

  - if node bin/checkpack.js browserify -e tests/bad_build.ts --validate; then (exit 1) else (exit 0) fi
  - node bin/checkpack.js browserify -e tests/good_build.ts --validate
